#define POPUP_WIDTH 280.0
#define POPUP_HEIGHT 340.0
#define WHITE_CALIBRATE 0.95
#define ALPHA 0.95
#define TASK_HEIGHT 35.0
#define TASK_BOX_HEIGHT 35.0
#define TASK_WIDTH 260.0
#define TASK_PADDING_LEFT -1.0
#define NEW_TASK_PADDING 10.0


#define TABLE_HEIGHT 0.8 * POPUP_HEIGHT
#define TEXT_HEIGHT POPUP_HEIGHT - TABLE_HEIGHT


